### ISSUE TITLE
unit testing / CI

### ISSUE THREAD

**Issue by DanielRuf** [eykhagen/strest#4]
So far I see no unit tests for strest and no Travis CI / AppVeyor setup.

We should have this to catch any bugs.

**Comment by eykhagen** [comment]
I agree! :+1:

**Comment by eykhagen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrating TravisCI](https://trello.com/c/e7wPresp/4-integrating-travisci)

**Comment by eykhagen** [comment]
#8 
Currently working on additional test suites 👍
