### ISSUE TITLE
Log output invisible on Solarized color scheme

### ISSUE THREAD

**Issue by alanorth** [eykhagen/strest#5]
It took me a few minutes to realize that the log output was not missing, but simply colored in such a way that makes it invisible in terminals using the Solarized color scheme. Selecting the text shows the log output.

Before:

![solarized-colors-bad-fs8](https://user-images.githubusercontent.com/191754/45282596-0d17b200-b4e4-11e8-8522-0ba9748d833e.png)

After:

![solarized-colors-highlited-fs8](https://user-images.githubusercontent.com/191754/45282612-130d9300-b4e4-11e8-8753-4ec385460ff4.png)

**Comment by eykhagen** [comment]
Thanks for your issue. I will fix this asap :+1:

**Comment by eykhagen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Log output invisible on Solarized color scheme bug](https://trello.com/c/bqTnz40i/3-log-output-invisible-on-solarized-color-scheme-bug)

**Comment by eykhagen** [comment]
You can now fix it yourself by creating a config file and changing the hex code of the `secondaryColor`. 🎉  #13
